version: 1.0.{build}
image: 
  - Visual Studio 2017
  #- Ubuntu
environment:
  matrix:
    - ARCH: amd64
    - ARCH: arm 
    - ARCH: arm64
    - ARCH: ppc64le
    - ARCH: s390x
  DOCKER_USER:
    secure: JapmC7j5F0mY3j/MVzU+Cw==
  DOCKER_PASS:
    secure: QGlCLNWzPD0HL8ipkohVic45/yU3bVOdjn0IiV6NnSQ=
matrix:
  exclude:
    - image: Visual Studio 2017
      ARCH: arm
    - image: Visual Studio 2017
      ARCH: arm64
    - image: Visual Studio 2017
      ARCH: ppc64le
    - image: Visual Studio 2017
      ARCH: s390x
branches:
  except:
    - master
stack: 
  - node 9, go 1.10
install:
  - yarn install
  - npm install -g rebase-docker-image
init:
  - sh: export IMAGE=linux
  - cmd: SET IMAGE=windows
  - ps: >-
      if (!(Test-Path ~/.docker)) { mkdir ~/.docker };
      Set-Content -Value '{ "experimental": "enabled" }' -Path ~/.docker/config.json -Encoding Ascii
build_script:
  - sh: yarn grunt release:$IMAGE:$ARCH
  - cmd: yarn grunt release:%IMAGE%:%ARCH%
  - sh: sudo bash build/ci-linux.sh $IMAGE $ARCH $DOCKER_USER $DOCKER_PASS $APPVEYOR_REPO_BRANCH $APPVEYOR_PULL_REQUEST_NUMBER
  - cmd: powershell -Command "& .\\build\\ci-windows.ps1"